CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210806071539_A') THEN
    CREATE SCHEMA IF NOT EXISTS dbo;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210806071539_A') THEN
    CREATE TABLE dbo.a (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        key text NOT NULL,
        CONSTRAINT pk_a_constraint_type PRIMARY KEY (id),
        CONSTRAINT ak_a_constraint_type_key UNIQUE (key)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210806071539_A') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210806071539_A', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


START TRANSACTION;

DO $$
BEGIN
    --something wrong
    sequal;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220101011539_B') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220101011539_B', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220916171539_C') THEN
    CREATE TABLE dbo.c (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        key text NOT NULL,
        CONSTRAINT pk_c_constraint_type PRIMARY KEY (id),
        CONSTRAINT ak_c_constraint_type_key UNIQUE (key)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220916171539_C') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220916171539_C', '5.0.7');
    END IF;
END $$;
COMMIT;